### ISSUE TITLE
Discoverability of assets

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#118]
- [x] most recent published assets
- [ ] most popular assets
- [x] categories list
- [ ] search results ordering

Channels with reward system:

- Health
- Mobility
- Nature
- Impact

**Comment by Kwinten-C** [comment]
1. V1: easiest and quickest implementation:
- most popular data sets (by number of unique downloads)
- recenly published data sets
- explore by categoriesV3
2. V2: channels challenge
contribute data to a project (MOBI, connectedLife)
3. V3: Implement curation

![commons-discovery](https://user-images.githubusercontent.com/39778584/57441005-570a9080-7249-11e9-80a1-a686f1ff3356.png)
