### ISSUE TITLE
category URL is wrong

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/commons#133]
## Current Behavior

Go to `History` tab. 
Go to one of the previously published assets. 
There is a smaller `History` link, it points to; `https://commons.oceanprotocol.com/search?text=History`

Remove URL or update?

**Comment by kremalicious** [comment]
You used the category "History" for that asset so the link to the category search is shown. So far we did not have a category search, but it has been added in https://github.com/oceanprotocol/commons/pull/125

**Comment by kremalicious** [comment]
Also the current url is actually working. What's not working is that it shows the highest search results match first because Aquarius defaults to ascending order with no way of changing it https://github.com/oceanprotocol/aquarius/issues/179

**Comment by MarcusJones** [comment]
Thanks, my mistake, the history link is correct. I guess you changed the scope of the issue, or just close if you want.
