### ISSUE TITLE
It's not necessary to initialize the service agreement for each download

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/commons#141]
Every time a user click the "GET FILE" button a new service agreement is initialized on-chain. This is not necessary when the user already have a valid service agreement for the same DID. Also applies for assets with multiple files, the first file you try to download you initialize the service agreement, after of that you can call directly the consume method.

**Comment by Pedro-vk** [comment]
To detect if it has been ordered before we can use `await ocean.assets.consumerAssets('0x...')`. It returns an array with all the consumable DIDs, but it shouldn't be a performance issue, but we should keep it in mind.
