### ISSUE TITLE
Commons Not Running Properly (CORS Issue?)

### ISSUE THREAD

**Issue by yupjpn** [oceanprotocol/commons#168]
## Expected Behavior

I am expecting Commons to run normally on my local machine without errors. Note that I have not made any changes to the code and have followed the instructions on the documentation line-by-line.

## Current Behavior

<img width="554" alt="Screen Shot 2019-07-01 at 4 51 39 PM" src="https://user-images.githubusercontent.com/42753186/60449882-840f6a00-9c20-11e9-98ab-5e7bd5a85098.png">

## Step to Reproduce the Problem

1. Clone and run Commons on local machine according to README

### Possible Solution

Commons actually worked perfectly until someone updated Barge and Commons a few days ago. Maybe the recent commits are causing this problem? 

## Specifications

* Version: 0.9.7
* Python: 2.7
* Solidity: Don't think I have this installed (then again, was not specified in documentation)
* JavaScript: Not sure how to check this
* Node: 10.16.0
* OS: macOS Mojave v10.14

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by wlihui7** [comment]
Hi I'm also getting this error when I try to run Commons locally

**Comment by jernejpregelj** [comment]
Hi @yupjpn @wlihui7 domains of services were updated yesterday. Here are the new ones:
Node: `https://nile.dev-ocean.com`
Aquarius: `https://aquarius.nile.dev-ocean.com`
Brizo: `https://brizo.nile.dev-ocean.com`
Secret store: `https://secret-store.nile.dev-ocean.com`
Faucet: `https://faucet.nile.dev-ocean.com`
Brizo address: `0x376817c638d2a04f475a73af37f7b51a2862d567`
