### ISSUE TITLE
Burner Wallet integration

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/commons#169]
Based on #139 , it would be necessary to integrate a Burner Wallet in Ocean commons.
The UX/UI flow is pending to be defined.

**Comment by kremalicious** [comment]
As a general principle: make it possible so all actions in Commons can be used as frictionless as possible, so users don't even have to think about wallet stuff.

### Non-Web3

Just like now, users can search only. 

### Web3: default to burner wallet

User can do search/publish/consume right away. This means we create a burner wallet by default, connected to the network Aquarius/Brizo is connected to. This will make the account status indicator green.

We inform user about the burner wallet usage:
- in `Web3message`: make it visually clear shown account is burner wallet. And show action `Change Wallet` to switch to MetaMask
- `Web3message` is then only shown in Publish flow, and additionally under files in consume flow
- in Account popup: small label under account or something
- on About page: above versions component we should add an extended `Web3message` showing the seed phrase and all

### Web3: MetaMask

Switching to MetaMask can be invoked with the action in `Web3message`. This will open a Modal with decision screen, where burner wallet is selected by default, and MetaMask can be selected. Selecting MetaMask starts the MetaMask auth flow and at its end (when account is detected) Modal is closed and UI switches to new account. 

We should also persist this user selection, so storing e.g. in `localStorage` that user has selected MetaMask ( like `prefersMetaMask`), so if user has this in `localStorage` on next visit, we switch to it automatically.

The `Change Wallet` action in `Web3message` is also shown in this combination, allowing user to switch to burner wallet. When user switches to burner wallet, the `prefersMetaMask` item in `localStorage` needs to be removed.
