### ISSUE TITLE
Support of basic assets management

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/commons#170]
To reduce the possibility of users publishing bad metadata in the commons marketplace, it would be necessary to have an independent page that allows to enable or disable assets from the Commons Marketplace.

This simple application must support giving a DID, to enable/disable this asset (using Aquarius under the hood). If the asset is disabled will not be visible in the commons marketplace.

This application must be configured to be visible only in the internal network, communicating with Aquarius (pacific) and having a user/password authentication (NGINX).

Tasks:

- [x] Creation of the one-page application supporting the enabling/disabling of assets via Aquarius
- [ ] Packaging of the application as a docker container
- [ ] Deployment in K8s 
- [ ] Configuration of Nginx to expose the application thru HTTPS and using user/password

**Comment by kremalicious** [comment]
With this scope, I would suggest moving this to its own repo as an independent project, mainly because of deployment. Cause we would have to change the delivery of the whole commons, we don't run that on Nginx right now.

The network restriction should only be done if we also have VPN access to our network.

On the other hand, can't we also solve this via account whitelisting? Meaning we define a bunch of accounts we control, and if those accounts look at an asset we show a enable/disable link?

**Comment by jernejpregelj** [comment]
Admin app currently in same folder in [admin-spa](https://github.com/oceanprotocol/commons/tree/feature/admin-spa) branch.
Admin app currently works only with spree network and uses aquarius api to retire asset. Button to retire can be found on bottom when opening asset.

**Comment by kremalicious** [comment]
As we see it there are 2 options, where option 1 has most advantage from devops perspective, and option 2 is better from product design perspective:

1. Standalone admin app

We create standalone admin app in separate repo. This would mean we can deploy individually, and lock it down however we like on the server level.

The main drawback of this solution is duplication and maintenance. We essentially would create another interface for the same thing: asset search, asset list, asset detail, retiring. And in future there would be more overlap, e.g. for metadata editing already done in https://github.com/oceanprotocol/commons/pull/108. From product design perspective it makes sense allowing owner of asset and admins to do editing/retiring of an asset so we would go a path where we have to duplicate those actions in 2 different apps.

2. Admin mode

We introduce an admin mode in existing app. This could be done by whitelisting selected accounts as environment variables. In UI we detect that, and show actions only when one of the whitelisted accounts is used. So an admin is someone using Commons with one of the whitelisted accounts. It would also show market operators how to deal with restricted actions in a marketplace UI.

The interface for that is kinda already existing in https://github.com/oceanprotocol/commons/pull/108 where currently it's based on the owner of an asset, but easy to extend that to admins too:

<img width="811" alt="Screen Shot 2019-07-05 at 11 56 48" src="https://user-images.githubusercontent.com/90316/60714779-026b5500-9f1c-11e9-92db-6e39480c7bf9.png">

Additionally, we show certain search query actions to admins only, e.g. "Show all retired assets", and in general include retired assets in all search queries for admins. 

The main drawback of this solution is that we can't lock it down on server level like solution 1. And we expose the API call. But it might not matter, API is documented anyway, and the `DELETE` call in Aquarius is blocked there on nginx level. We'll send user/pass defined as environment variable along from frontend to bypass that. This implies we would need to use the server part of Commons as a proxy to hide the user/pass in API call.
