### ISSUE TITLE
back button sometimes produces the "No Data Sets Found" message

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#175]
From [Gitter](https://gitter.im/oceanprotocol/Lobby?at=5d23ce660c8daa1686adb8cd)
> For example: selecting the Image Recognition category, going to the last page, selecting the "CIFAR_10_small" dataset, and hitting the back button.

The url then ends up with empty `text` query, resulting in 0 results: `https://commons.oceanprotocol.com/search?text=&page=11`

**Comment by jernejpregelj** [comment]
Code responsible for this bug is reworked in https://github.com/oceanprotocol/commons/pull/183
