### ISSUE TITLE
Unable to publish asset using Metamask. Burner Wallet works though.

### ISSUE THREAD

**Issue by innoprenuer** [oceanprotocol/commons#186]
## Expected Behavior

I can use Metamask to publish asset into Pacific network.  
## Current Behavior

When Metamask is used to publish, Commons shows "Something went wrong. try again?" error message after 3 signing. And it doesn't go through even after click on 'try again' link.

## Steps

Try to register asset using Metamask in [Commons](https://commons.oceanprotocol.com/) marketplace. After completing all steps and signing 3 times, when its status is 'Registering DID', it displays "Something went wrong. try again?" error.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

[commons.oceanprotocol.com-1565279867893.log](https://github.com/oceanprotocol/commons/files/3482626/commons.oceanprotocol.com-1565279867893.log)

**Comment by kremalicious** [comment]
So this error looks like some Plecos metadata validation failing on Aquarius:

```
aquarius.commons.oceanprotocol.com/api/v1/aquarius/assets/ddo:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
2.4abbdd9f.chunk.js:1 Error requesting [POST] https://aquarius.commons.oceanprotocol.com/api/v1/aquarius/assets/ddo
e.dispatch @ 2.4abbdd9f.chunk.js:1
2.4abbdd9f.chunk.js:1 Response message: 
[{"message":"[] is not of type 'string'","path":"base/categories/0"}]
```

I just tested but get in console:

```
error: Returned error: Request has been rejected because of queue limit.
```

Where I have no idea what that is, some limit setup in Aquarius or somewhere else

**Comment by kremalicious** [comment]
Now it works for me, I think we just crashed Aquarius and it came back up now

<img width="1214" alt="Screen Shot 2019-08-08 at 18 12 14" src="https://user-images.githubusercontent.com/90316/62719399-27198780-ba08-11e9-8410-e4aac9c12269.png">

**Comment by alexcos20** [comment]
works fine for me on 2201 network
![metamask_publish_ok](https://user-images.githubusercontent.com/7489447/62765688-4e6c6500-ba99-11e9-826d-f98d58ead136.jpg)

**Comment by jernejpregelj** [comment]
This was resolved if I'm correct? Reopen the issue if not.
