### ISSUE TITLE
Don't display assets that are not free

### ISSUE THREAD

**Issue by tomafc330** [oceanprotocol/commons#212]
## Expected Behavior
Currently, assets are being displayed even though it's not free on the commons website:

In Search.tsx:74

```
        const queryValues =
            searchCategories !== '' && searchTerm !== ''
                ? { text: [searchTerm], categories: [searchCategories] }
                : searchCategories !== '' && searchTerm === ''
                ? { categories: [searchCategories] }
                : { text: [searchTerm] }
```

It looks like we might need to add a search filter for price == 0.0

### Possible Solution

I tried to add in a search modifier `price: '0.0'` but to no avail. I looked at the Aqaurius api and it seems to take that (ie. if I do something like `const queryValues = { tags: [searchTerm], price: '1.0' }` it seems to work). 

However, I can't get it to work with `text` and `price` together. If someone can point me to the right direction, I can address this issue :)

Please include any relevant log snippets or files here.

**Comment by innoprenuer** [comment]
Change the label to WIP once someone starts working on it. I will do the same.
