### ISSUE TITLE
issues with installations

### ISSUE THREAD

**Issue by areaboy** [oceanprotocol/commons#214]
Hi everyone. Am trying to install this app. when I run **npm instal**l, am having error

`'.' is  not recognized as internal or external command when running npm`

am using using windows 7 OS
What could be the issue.

Thanks

**Comment by kremalicious** [comment]
This seems related to your node.js installation and is outside the scope of Ocean Protocol. Just googling that error turns up many solutions

https://www.google.es/search?q=%27.%27+is+not+recognized+as+internal+or+external+command+when+running+npm&ie=UTF-8&oe=UTF-8&hl=en-us
