### ISSUE TITLE
add file type & categories icons

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#22]

**Comment by Kwinten-C** [comment]
Publish file types are added to https://github.com/oceanprotocol/commons/issues/96

**Comment by Kwinten-C** [comment]
If possible to retrieve from the back end:

- add file type in full asset view
- add file name to distinguish (sometimes a data set has files of equal size, making them seem identical)
- add file type icon for most common types

![fullassetview-file info](https://user-images.githubusercontent.com/39778584/57462688-a23c9780-7279-11e9-86c3-93168cfb18c2.png)
