### ISSUE TITLE
add links & custom image

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#54]
Move over UI for adding `links` from pleuston and add to publish flow. Also implement functionality from there to add an image by adding a special `link` type and if present, use that image in place of category images.

**Comment by Kwinten-C** [comment]
**Download ZIP files for category banners**
Category (fallback) images changed to 2:1 format with full width size, based on current data asset view (645x323px).
Available in both 1x and 2x scale. 

1x scale .JPG at 100% quality:
[banners 1x-100.zip](https://github.com/oceanprotocol/commons/files/3156695/banners.1x-100.zip)

2x scale .JPG at 80% quality - part 1:
[banners 2x-80 part1.zip](https://github.com/oceanprotocol/commons/files/3156699/banners.2x-80.part1.zip)

2x scale .JPG at 80% quality - part 2:
[banners 2x-80 part2.zip](https://github.com/oceanprotocol/commons/files/3156697/banners.2x-80.part2.zip)

Sample preview for quick reference:
![samplebanners1](https://user-images.githubusercontent.com/39778584/57366964-62e24e00-7188-11e9-8f0f-165c398dbf54.jpg)
![samplebanners2](https://user-images.githubusercontent.com/39778584/57366970-65dd3e80-7188-11e9-936a-f54a76cdb637.jpg)
