### ISSUE TITLE
 initial loading of Ocean instance takes long time

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#63]
For whatever reason the initial `Ocean.getInstance()` is taking a long time (~10-20s) when connecting to Nile. Investigate and make it as fast as possible.

The UI hangs for a long time on this line: https://github.com/oceanprotocol/commons/blob/master/client/src/App.tsx#L160

where the `provideOcean` function is calling this: https://github.com/oceanprotocol/commons/blob/master/client/src/ocean.ts#L40

### Fixes

- https://github.com/oceanprotocol/squid-js/pull/190
- https://github.com/oceanprotocol/commons/pull/101

**Comment by jernejpregelj** [comment]
https://github.com/oceanprotocol/squid-js/pull/190

**Comment by kremalicious** [comment]
Fix from #190 has been deployed. Additionally, #101 introduces more fine-grained loading and feedback during initial bootstrap phase
