### ISSUE TITLE
Search does not work properly

### ISSUE THREAD

**Issue by w1kke** [oceanprotocol/commons#75]
I added a dataset called MNIST and then tried to find it via the search functionality but I got this result instead of what I would expect:
![Seach_Bug](https://user-images.githubusercontent.com/921146/55720237-a4080680-5a00-11e9-8d05-54eff16c67d7.png)

**Comment by kremalicious** [comment]
thanks! We're on it https://github.com/oceanprotocol/aquarius/issues/169

**Comment by kremalicious** [comment]
we deployed a fix so this search is now actually showing results:

<img width="1148" alt="Screen Shot 2019-04-08 at 17 47 25" src="https://user-images.githubusercontent.com/90316/55737911-64ecac00-5a26-11e9-8dd7-a146538dd8bf.png">
