### ISSUE TITLE
More feedback for all network interactions

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/commons#84]
This is based on some feedback we got via Gitter, e.g.

- https://gitter.im/oceanprotocol/Lobby?at=5cab8526759abc043c8a24de
- https://gitter.im/oceanprotocol/Lobby?at=5caba88b31aec969e873020f

In the final steps of the publishing flow, one must give four MetaMask confirmations (by my count). That might be familiar to people in the crypto-blockchain world, but it's weird, unexpected and baffling for others.

Suggestions:

- Tell them how many MetaMask "confirmations" they will have to do. Maybe list them all? They aren't all called confirmations; some are about signing. Maybe show partial screenshots?
- Help them find and reveal the MetaMask dialog boxes? I find I sometimes have to click on the MetaMask icon near the top right corner of my Chrome browser.
- Note that there may be a time delay until the next MetaMask step is required?
- Give visual or text feedback on where they are (among the steps), if possible.

Same for the consuming flow, needs feedback about the exact states the user is in.

### ToDo

- [x] feedback messages during consume flow (#110)
- [x] feedback during publish flow (#151)

**Comment by kremalicious** [comment]
Whenever we have a network interaction we should use a UI pattern like this:

<img width="399" alt="Screen Shot 2019-04-10 at 12 23 05" src="https://user-images.githubusercontent.com/90316/55871688-78fdee00-5b8b-11e9-9a2d-a4954c87fa00.png">

Question is how to get those events. A quick fix could be to use the console messages squid-js is pushing during publish & consume flows.

**Comment by jernejpregelj** [comment]
> communicate directly to Ethereum blockchain to get transaction infos
We don't have to communicate directly with Ethereum blockchain. Squid-js acts as a process/state manager for the user so just getting information from squid-js would be enough. Most efficient way to implement would be to use some event system to output events outside squid-js. This way the change in squid api would be just to add lets say events instance (ocean.events) and app would attach listener to it.
