### ISSUE TITLE
Changing metadata

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#95]
We start simple:

- allow editing of all metadata fields which don't change the asset `checksum`
- introduce edit mode for an asset, can be entered with a button on asset details view
- edit mode switches displayed metadata to input/select fields with the currently set value filled in
- shows help text for all metadata which can't be changed 

---

- #31 might have already something we need for that
- server: changing/retiring metadata in #106
- change in Aquarius https://github.com/oceanprotocol/aquarius/issues/177

**Comment by jernejpregelj** [comment]
Updated PR with changing/retiring metadata https://github.com/oceanprotocol/commons/pull/106
