### ISSUE TITLE
add type to publish flow

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#96]
Add `select` to ask for type of an asset. Make it optional, but still default to `dataset`

**Comment by jernejpregelj** [comment]
It's hard to explain in select difference between dataset, workflow, training model results....
Would be nice to have like a starting point before entering publish flow with little explanation.

This would be quick example what I have in mind:
![Screenshot 2019-04-17 at 16 44 00](https://user-images.githubusercontent.com/7147341/56297267-5aba6400-6130-11e9-96b8-f7c3ca9af699.png)

**Comment by jernejpregelj** [comment]
PR in progress https://github.com/oceanprotocol/commons/pull/111

**Comment by Kwinten-C** [comment]
**Marketplace Type Icons for publish flow:**
"Algorithm" to be changed to "script" or "pipeline".
Inline SVG can be downloaded here:
[commons-types.zip](https://github.com/oceanprotocol/commons/files/3152946/commons-types.zip)

![marketplace-files-01](https://user-images.githubusercontent.com/39778584/57304855-5b676a00-70e0-11e9-8f3e-8c22550ead18.png)

**Comment by Kwinten-C** [comment]
Alternative lay-out with white on gradient fill and also old container icon, not withheld:

![view_icons_solid](https://user-images.githubusercontent.com/39778584/57364203-029cdd80-7183-11e9-9fe9-20fd58b31598.png)
